#!/bin/bash

pushd ../Stntuple ; scripts/build_config ; popd ;


dir=include
if [ ! -d ../$dir/su2020 ] ; then mkdir -p ../$dir/su2020 ; fi

package=gaasAna

# echo pwd  `pwd`

#------------------------------------------------------------------------------
# 'gaasAna' and its subpackages
#------------------------------------------------------------------------------
if [ ! -d ../$dir/$package ] ; then mkdir -p ../$dir/$package ; fi

for d in ana obj ; do
    if [ ! -e ../$dir/$package/$d ] ; then 
	echo `pwd`$0 : creating symbolic link ../$dir/$package/$d
	ln -s ../../$package/$d/$d ../$dir/$package/$d
    fi
done
